version: 2.1

defaults: &defaults
  docker:
    - image: ruby:2.7.4

only_master: &only_master
  filters:
    branches:
      only:
        - master

commands:
  install_java:
    steps:
      - run: ./scripts/ci/common/install-openjdk.sh
  configure_release:
    steps:
      - run: ./scripts/ci/common/upgrade-gpg.sh
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/common/configure-clojars.sh

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - install_java
      - run: ./scripts/ci/steps/build.sh
  test:
    <<: *defaults
    steps:
      - checkout
      - install_java
      - run: ./scripts/ci/steps/test.sh
  prerelease:
    <<: *defaults
    steps:
      - checkout
      - install_java
      - configure_release
      - run: ./scripts/ci/steps/prerelease.sh
  release:
    <<: *defaults
    steps:
      - checkout
      - install_java
      - configure_release
      - run: ./scripts/ci/steps/release.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - prerelease:
          <<: *only_master
          requires:
            - test
      - hold:
          <<: *only_master
          type: approval
          requires:
            - prerelease
      - release:
          <<: *only_master
          requires:
            - hold